import gpytorch
from gpytorch.constraints import Interval


def init_kernel(name, dim, params, scale=True):
    # struct(... % LIN
    # 'covFcn', {'{@covPoly, ''eye'', 1}'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {log([0.1 1])})}, ...
    # 'hypRestartSigma', {diag([2 5 5 0.01])}...
    # ), ...
    if name == 'lin':
        kernel = gpytorch.kernels.LinearKernel(**params)

    # struct(... % QUAD
    # 'covFcn', {'{@covPoly, ''eye'', 2}'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {log([0.1 1])})}, ...
    # 'hypRestartSigma', {diag([2 5 5 0.01])}...
    # ), ...
    elif name == 'quad':
        kernel = gpytorch.kernels.PolynomialKernel(2, **params)

    # struct(... % SE
    # 'covFcn', {'@covSEiso'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {log([0.5 2])} )}, ...
    # 'hypRestartSigma', {diag([2 5 5 0.01])}...
    # ), ...
    elif name == 'rbf':
        kernel = gpytorch.kernels.RBFKernel(**params)

    # struct(... % MATERN5
    # 'covFcn', {'{@covMaterniso, 5}'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {log([0.5 2])} )}, ...
    # 'hypRestartSigma', {diag([2 5 5 0.01])}...
    # ), ...
    elif name == 'matern':
        kernel = gpytorch.kernels.MaternKernel(nu=2.5, **params)

    # struct(... % RQ
    # 'covFcn', {'@covRQiso'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {log([0.5 2 0.1])} )}, ...
    # 'hypRestartSigma', {diag([2 5 5 5 0.01])}...
    # ), ...
    elif name == 'rq':
        kernel = gpytorch.kernels.RQKernel(**params)

    # struct(... % NN(ARCSIN)
    # 'covFcn', {'@covNNone'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {log([0.5 2])} )}, ...
    # 'hypRestartSigma', {diag([2 5 5 0.01])}...
    # ), ...
    elif name == 'nn_arcsin':  # TODO
        raise NotImplementedError('TODO')

    # struct(... % ADD
    # 'covFcn', {'{@covADD, {[1 max(2, ceil(obj.dim/2))], @covSEisoU}}'}, ...
    # 'hyp', {struct('lik', log(0.1), ...
    # 'cov', {[log(0.5) 1 1]} )}, ...
    # 'hypRestartSigma', {'diag([2 2 * ones(1, obj.dim) 2 2 0.01])'}...
    # ), ...
    elif name == 'add':
        # U - no outputscale inside, just outside
        base = gpytorch.kernels.RBFKernel()  # ARD=None -> Isometric
        init_lengthscale(base, params)
        kernel = gpytorch.kernels.AdditiveStructureKernel(base, num_dims=dim)

    # struct(... % SE + QUAD
    # 'covFcn', {'{@covSum, {@covSEiso, {@covPoly, ''eye'', 2}}}'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {log([0.5 2 0.1 1])} )}, ...
    # 'hypRestartSigma', {diag([2 2 2 2 2 0.01])}...
    # ), ...
    elif name == 'se_quad':
        rbf = gpytorch.kernels.RBFKernel(**params)
        poly = gpytorch.kernels.PolynomialKernel(2, **params)
        init_lengthscale(rbf, params)
        init_lengthscale(poly, params)
        kernel = gpytorch.kernels.AdditiveKernel(rbf, poly)

    # struct(... % GIBBS
    # 'covFcn', {'{@covSEvlen, {@meanSum, {@meanLinear, @meanConst}}}'}, ...
    # 'hyp', {struct('lik', log(0.01), ...
    # 'cov', {'[zeros(1, obj.dim) 0.5 log([2])]'} )}, ...
    # 'hypRestartSigma', {'diag([2 10 * ones(1, obj.dim) 10 5 0.01])'}...
    # ), ...
    # }
    elif name == 'gibbs':  # TODO
        raise NotImplementedError('TODO')
    #       SPECTRAL MIXTURE
    #
    #
    elif name == 'spectral_mixture':
        kernel = gpytorch.kernels.SpectralMixtureKernel(4, ard_num_dims=dim)  # Q = 4 Wilson 2016 Deep Kernel Learning
    else:
        raise ValueError(f'Unknown kernel {name}')

    init_lengthscale(kernel, params)

    if scale:  # outputscale ~ signal variance
        kernel = gpytorch.kernels.ScaleKernel(kernel)
    return kernel


def init_lengthscale(kernel, params):
    try:
        kernel.register_constraint('raw_lengthscale', Interval(1e-2, 100))
        kernel.initialize(lengthscale=params['lengthscale'])
    except RuntimeError:
        pass
